language: go
go:
    - 1.5
    - tip
install:
    - go get github.com/Sirupsen/logrus
    - go get github.com/satori/go.uuid
    - go get golang.org/x/net/ipv4
sudo: false
notifications:
    email: false